/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import BO.CitaBO;
import BO.MedicoBO;
import BO.PacienteBO;
import DTO.CitaNuevaDTO;
import DTO.MedicoViejoDTO;
import Entidades.Cita;
import Entidades.Medico;
import Exception.NegocioException;
import configuracion.DependencyInjector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import sesionUsuario.SesionUsuario;

/**
 *
 * @author jorge
 */
public class AgendarCitaPaciente extends javax.swing.JFrame {
    private MedicoBO medicoBO = DependencyInjector.crearMedicoBO();
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private CitaBO citaBO = DependencyInjector.crearCitaBO();

    /**
     * Creates new form AgendarCitaPaciente
     */
    public AgendarCitaPaciente() {
        initComponents();
        
        // Llenar comboEspecialidad
        String[] especialidades = {"cardiologia", "oftamologia", "ortopedia", "neurologia", "nefrologia"};
        comboEspecialidad.setModel(new DefaultComboBoxModel<>(especialidades));
            // ActionListener para comboEspecialidad
        comboEspecialidad.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String especialidadSeleccionada = (String) comboEspecialidad.getSelectedItem();
                    List<MedicoViejoDTO> medicosDisponibles = medicoBO.obtenerMedicosActivos();
                    
                    comboMedicoDisponible.removeAllItems();
                    for (MedicoViejoDTO medico : medicosDisponibles) {
                        if(medico.getEspecialidad().toString().equalsIgnoreCase(especialidadSeleccionada))
                            comboMedicoDisponible.addItem(new MedicoComboBoxItem(medico));
                    }
                } catch (NegocioException ne) {
                    Logger.getLogger(AgendarCitaPaciente.class.getName()).log(Level.SEVERE, null, ne);
                }
            }
        });
        
       
        // ActionListener para comboMedicoDisponible
        comboMedicoDisponible.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MedicoComboBoxItem medicoItem = (MedicoComboBoxItem) comboMedicoDisponible.getSelectedItem();
                if (medicoItem != null) {
                    MedicoViejoDTO medicoSeleccionado = medicoItem.getMedico();
                    // Ahora tienes el objeto Medico completo y puedes acceder a su ID y otros datos
                    int idMedico = medicoSeleccionado.getIdMedico();
                    List<Map<String,Object>> citasDisponibles;
                    try {
                        //Date to LocalDate
                            LocalDate fechaLocalDate = jDateChooser1.getDate().toInstant()
                                                          .atZone(ZoneId.systemDefault())
                                                          .toLocalDate();
                        citasDisponibles = pacienteBO.consultarCitasDisponibles(idMedico, fechaLocalDate.toString());
                        comboHorario.removeAllItems();
                        for (Map<String, Object> citasDisponible : citasDisponibles) {
                            comboHorario.addItem(citasDisponible.get("horaInicio").toString() + " - " + citasDisponible.get("horaFin").toString());
                        }
                    } catch (NegocioException ex) {
                        Logger.getLogger(AgendarCitaPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        comboEspecialidad = new javax.swing.JComboBox<>();
        comboMedicoDisponible = new javax.swing.JComboBox<>();
        comboHorario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        comboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardiologia", "oftamologia", "ortopedia", "neurologia", "nefrologia" }));
        comboEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecialidadActionPerformed(evt);
            }
        });

        comboHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHorarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Especialidad:");

        jLabel2.setText("Seleccionar Medico Disponible:");

        jLabel3.setText("Horario de atencion:");

        btnConfirmar.setText("Confirmar Cita");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setText("fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 310, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEspecialidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboHorario, 0, 137, Short.MAX_VALUE)
                                    .addComponent(comboMedicoDisponible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMedicoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MenuPacientes menuPacientes = new MenuPacientes();
        menuPacientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void comboEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspecialidadActionPerformed

    private void comboHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHorarioActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        try {
            // Validación 1: Médico seleccionado
            MedicoComboBoxItem medicoSeleccionado = (MedicoComboBoxItem) comboMedicoDisponible.getSelectedItem();
            if (medicoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione un médico.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si no hay médico seleccionado
            }
            int idMedico = medicoSeleccionado.getMedico().getIdMedico();

            // Validación 2: Fecha seleccionada
            Date fechaSeleccionada = jDateChooser1.getDate();
            if (fechaSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si no hay fecha seleccionada
            }
            LocalDate fechaLocalDate = fechaSeleccionada.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            // Validación 3: Horario seleccionado
            String fechas = (String) comboHorario.getSelectedItem();
            if (fechas == null || fechas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione un horario.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si no hay horario seleccionado
            }
            String[] fechasSplit = fechas.split(" - ");
            if (fechasSplit.length != 2) {
                JOptionPane.showMessageDialog(this, "Formato de horario incorrecto.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salir del método si el formato del horario es incorrecto
            }
            LocalTime fechaInicio = LocalTime.parse(fechasSplit[0]);
            LocalTime fechaFin = LocalTime.parse(fechasSplit[1]);

            // Validación 4: Fecha de cita no puede ser en el pasado
            if (fechaLocalDate.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "La fecha de la cita no puede ser en el pasado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validación 5: Hora de inicio no puede ser después de la hora de fin
            if (fechaInicio.isAfter(fechaFin)) {
                JOptionPane.showMessageDialog(this, "La hora de inicio no puede ser después de la hora de fin.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Crear y agendar la cita
            int idPaciente = SesionUsuario.getPaciente().getIdPaciente();
            System.out.println(idPaciente);
            System.out.println("Paciente: " + SesionUsuario.getPaciente().toString());
            CitaNuevaDTO citaDTO = new CitaNuevaDTO(idMedico, idPaciente,
                    fechaLocalDate, fechaInicio, fechaFin, Cita.EstadoCita.pendiente);
            System.out.println("CitaDTO: " + citaDTO.toString());
            citaBO.agendarCita(citaDTO);
            JOptionPane.showMessageDialog(this, "Cita creada con horario: " + fechaInicio + " - " + fechaFin, "Cita Agendada", JOptionPane.INFORMATION_MESSAGE);

        } catch (NegocioException ne) {
            Logger.getLogger(AgendarCitaPaciente.class.getName()).log(Level.SEVERE, null, ne);
            JOptionPane.showMessageDialog(this, ne.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) { // Capturar otras excepciones (por ejemplo, parseo de hora)
            Logger.getLogger(AgendarCitaPaciente.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboEspecialidad;
    private javax.swing.JComboBox<String> comboHorario;
    private javax.swing.JComboBox<MedicoComboBoxItem> comboMedicoDisponible;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    /**
     * Clase interna para almacenar al medico en la comvbox
     */
    private class MedicoComboBoxItem {
        private MedicoViejoDTO medico;

        public MedicoComboBoxItem(MedicoViejoDTO medico) {
            this.medico = medico;
        }

        public MedicoViejoDTO getMedico() {
            return medico;
        }

        @Override
        public String toString() {
            return medico.getNombre();
        }
    }

}
