/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import BO.MedicoBO;
import BO.PacienteBO;
import BO.UsuarioBO;
import DTO.UsuarioViejoDTO;
import Entidades.Usuario;
import Exception.NegocioException;
import configuracion.DependencyInjector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sesionUsuario.SesionUsuario;

/**
 *
 * @author jorge
 */
public class InicioSesion extends javax.swing.JFrame {
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private MedicoBO medicoBO = DependencyInjector.crearMedicoBO();
    private UsuarioBO usuarioBO = DependencyInjector.crearUsuarioBO();
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrarse");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Usuario o Correo:");

        jLabel2.setText("Ingrese Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtContra, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnIniciarSesion)
                .addGap(25, 25, 25)
                .addComponent(btnRegistro)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        Registro registro = new Registro(); // Crear la instancia de la otra pantalla
        registro.setVisible(true); // Hacer visible la nueva pantalla
        this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String entrada = txtUsuario.getText();
        String contrasenia = String.valueOf(txtContra.getPassword());

        // Validación 1: Campos no vacíos
        if (entrada.trim().isEmpty() || contrasenia.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si los campos están vacíos
        }

        // Validación 2: Longitud de contraseña mínima
        if (contrasenia.length() < 6) { // Ajusta la longitud mínima según tus requisitos
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación 3: Formato de correo electrónico
        if (entrada.contains("@")) { // Validación básica, puedes usar expresiones regulares para una validación más estricta
            if (!entrada.contains(".") || !entrada.contains("@")) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        try {
            UsuarioViejoDTO usuario = usuarioBO.iniciarSesion(entrada, contrasenia);

            if (usuario != null) {
                if (usuario.getTipo() == Usuario.TipoUsuario.paciente) {
                    SesionUsuario.setUsuario(pacienteBO.obtenerPacientePorCorreo(entrada));
                    JOptionPane.showMessageDialog(this, "Bienvenido paciente " + SesionUsuario.getPaciente().getNombre());
                    MenuPacientes menuPacientes = new MenuPacientes();
                    menuPacientes.setVisible(true);
                    dispose();
                } else if (usuario.getTipo() == Usuario.TipoUsuario.medico) {
                    SesionUsuario.setUsuario(medicoBO.obtenerMedicoPorCedula(entrada));
                    JOptionPane.showMessageDialog(this, "Bienvenido médico " + SesionUsuario.getMedico().getNombre());
                    MenuMedico menuMedicos = new MenuMedico();
                    menuMedicos.setVisible(true);
                    dispose();
                }
            } else {
                // Si no se encuentra ni paciente ni médico, mostrar error
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            if(usuario.getTipo().equals(Usuario.TipoUsuario.paciente)){
                SesionUsuario.setUsuario(pacienteBO.obtenerPacientePorCorreo(entrada));
            }else{
                SesionUsuario.setUsuario(medicoBO.obtenerMedicoPorCedula(entrada));
            }

        } catch (NegocioException ne) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ne.getMessage());
            JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + ne.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) { // Capturar otras excepciones (por ejemplo, NullPointerException)
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e.getMessage());
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
