/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import BO.PacienteBO;
import DTO.ConsultaUrgenciaDTO;
import Exception.NegocioException;
import configuracion.DependencyInjector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sesionUsuario.SesionUsuario;

/**
 *
 * @author jorge
 */
public class MenuPacientes extends javax.swing.JFrame {
    // Obtener instancia de PacienteBO desde DependencyInjector
    PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    
    /**
     * Creates new form MenuPacientes
     */
    public MenuPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgendarCita = new javax.swing.JButton();
        btnMisCitas = new javax.swing.JButton();
        btnConsultaSinCita = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgendarCita.setText("Agendar Cita");
        btnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarCitaActionPerformed(evt);
            }
        });

        btnMisCitas.setText("Mis Citas");
        btnMisCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisCitasActionPerformed(evt);
            }
        });

        btnConsultaSinCita.setText("Consulta sin Cita");
        btnConsultaSinCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaSinCitaActionPerformed(evt);
            }
        });

        btnPerfil.setText("Mi Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMisCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaSinCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnAgendarCita)
                .addGap(18, 18, 18)
                .addComponent(btnMisCitas)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaSinCita)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
    SesionUsuario.cerrarSesion();
    Inicio inicio= new Inicio(); // Crear la instancia de la otra pantalla
    inicio.setVisible(true); // Hacer visible la nueva pantalla
    this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
    AgendarCitaPaciente agendarCitaPaciente = new AgendarCitaPaciente(); // Crear la instancia de la otra pantalla
    agendarCitaPaciente.setVisible(true); // Hacer visible la nueva pantalla
    this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    private void btnMisCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisCitasActionPerformed
        CitasPacientes citasPacientes = new CitasPacientes(); // Crear la instancia de la otra pantalla
    citasPacientes.setVisible(true); // Hacer visible la nueva pantalla
    this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnMisCitasActionPerformed

    private void btnConsultaSinCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSinCitaActionPerformed
        ConsultaSinCita consultaSinCita = new ConsultaSinCita(); // Crear la instancia de la otra pantalla
        try {
            ConsultaUrgenciaDTO consultaUrgencia= pacienteBO.asignarMedicoUrgencia(SesionUsuario.getPaciente().getId_paciente());
            JOptionPane.showMessageDialog(this, "Consulta con: " + consultaUrgencia.getNombreMedico()+ " en el horario: " + 
                    consultaUrgencia.getHoraInicioConsulta() + " - " + consultaUrgencia.getHoraFinConsulta() + "Presentando el folio: " + consultaUrgencia.getFolio(), 
                    "Consulta sin cita creada", JOptionPane.INFORMATION_MESSAGE);
        } catch (NegocioException ne) {
            Logger.getLogger(MenuPacientes.class.getName()).log(Level.SEVERE, null, ne);
            JOptionPane.showMessageDialog(this, ne.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        consultaSinCita.setVisible(true); // Hacer visible la nueva pantalla
        this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnConsultaSinCitaActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
   PerfilPaciente perfilPaciente = new PerfilPaciente(); // Crear la instancia de la otra pantalla
    perfilPaciente.setVisible(true); // Hacer visible la nueva pantalla
    this.dispose(); // Cerrar la pantalla actual
    }//GEN-LAST:event_btnPerfilActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultaSinCita;
    private javax.swing.JButton btnMisCitas;
    private javax.swing.JButton btnPerfil;
    // End of variables declaration//GEN-END:variables
}
